# Generated by Django 5.1.6 on 2025-03-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_refacciones_costo_vehiculo_anio_vehiculo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
