# Generated by Django 5.1.6 on 2025-03-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='linea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
