# Generated by Django 5.1.6 on 2025-03-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_vehiculo_linea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refacciones',
            name='sock_minimo',
        ),
        migrations.AddField(
            model_name='refacciones',
            name='stock_minimo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
