# Generated by Django 5.1.6 on 2025-03-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_refacciones_sock_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='RFC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_representante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
