# Generated by Django 5.1.6 on 2025-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_proveedor_rfc_proveedor_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='num_telef',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
