# Generated by Django 5.1.6 on 2025-04-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_proveedor_num_telef"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientos",
            name="hora",
            field=models.TimeField(auto_now_add=True, default="20:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movimientos",
            name="fecha",
            field=models.DateField(auto_now_add=True),
        ),
    ]
