# Generated by Django 5.1.6 on 2025-04-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_movimientos_hora_alter_movimientos_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientos",
            name="nombre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
