# Generated by Django 5.1.6 on 2025-04-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_movimientos_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientos",
            name="placas",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
