# Generated by Django 5.1.6 on 2025-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_movimientos_placas'),
    ]

    operations = [
        migrations.AddField(
            model_name='refacciones',
            name='activo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
