# Generated by Django 5.2 on 2025-04-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_movimientos_placas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='empresa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.empresa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='empresa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.empresa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='operador_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.operador'),
        ),
    ]
