# Generated by Django 5.1.6 on 2025-04-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_refacciones_activo_usuario_activo_vehiculo_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="activo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="operador",
            name="activo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="activo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
