# Generated by Django 5.2 on 2025-04-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_operador_empresa_id_alter_vehiculo_empresa_id_and_more'),
        ('inventory', '0012_categoria_activo_operador_activo_proveedor_activo'),
    ]

    operations = [
    ]
