# Generated by Django 5.2 on 2025-04-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_merge_20250422_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='num_unidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
