# Generated by Django 5.2 on 2025-04-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_refacciones_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendimientoVehiculo',
            fields=[
                ('rendimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('km_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_recorrido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rendimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bomba', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('operador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.operador')),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vehiculo')),
            ],
        ),
    ]
