# Generated by Django 5.2 on 2025-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_rendimientovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimientovehiculo',
            name='activo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
