# Generated by Django 5.2 on 2025-04-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_rendimientovehiculo_bomba_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RendimientoVehiculo',
        ),
    ]
