# Generated by Django 5.2 on 2025-04-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_delete_rendimientovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_actualizacion_permisos',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
