# Generated by Django 5.1.6 on 2025-05-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_delete_rendimientovehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="operador_anterior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehiculos_anteriores",
                to="inventory.operador",
            ),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="operador_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehiculos_actuales",
                to="inventory.operador",
            ),
        ),
    ]
