# Generated by Django 5.1.6 on 2025-05-01 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_vehiculo_operador_anterior_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiculo",
            name="operador_anterior",
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="operador_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.operador",
            ),
        ),
    ]
