# Generated by Django 5.2 on 2025-04-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_usuario_ultima_actualizacion_permisos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_actualizacion_permisos',
        ),
    ]
