# Generated by Django 5.2 on 2025-05-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_usuario_ultima_actualizacion_permisos'),
        ('inventory', '0021_remove_vehiculo_operador_anterior_and_more'),
    ]

    operations = [
    ]
