# Generated by Django 5.2 on 2025-05-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_merge_20250502_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
