# Generated by Django 5.2 on 2025-05-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_usuario_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_updated',
        ),
    ]
