# Generated by Django 5.2 on 2025-05-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_usuario_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='refacciones',
            name='asignacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
