# Generated by Django 5.1.6 on 2025-05-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_remove_usuario_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="refacciones",
            name="linas",
            field=models.TextField(blank=True, null=True),
        ),
    ]
