# Generated by Django 5.2 on 2025-05-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_refacciones_asignacion'),
        ('inventory', '0025_refacciones_linas'),
    ]

    operations = [
    ]
