# Generated by Django 5.1.6 on 2025-05-13 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_merge_20250513_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refacciones',
            name='asignacion',
        ),
    ]
